export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const VERIFY_FAILURE = 'VERIFY_FAILURE';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const VERIFY_EMAIL_ERROR = 'VERIFY_EMAIL_ERROR';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
export const AUTH_LOADER = 'AUTH_LOADER';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_ERROR';
export const VERIFY_RESET_PASSWORD_SUCCESS = 'VERIFY_RESET_PASSWORD_SUCCESS';
export const VERIFY_RESET_PASSWORD_FAILURE = 'VERIFY_RESET_PASSWORD_FAILURE';
export const RESET_LOADER = 'RESET_LOADER';

export const VIEW_PROFILE = 'VIEW_PROFILE';
export const SHOW_CATEGORIES = 'SHOW_CATEGORIES';

export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const BADGE_COUNT = 'BADGE_COUNT';

export const IS_ADMIN = 'IS_ADMIN';
export const NOT_ADMIN = 'NOT_ADMIN';

export const IS_FETCHING = 'IS_FETCHING';
export const IS_PROFILE_FETCHING = 'IS_PROFILE_FETCHING';
export const IS_CAT_FETCHING = 'IS_CAT_FETCHING';
export const SHOW_DATA_LOADING = 'SHOW_DATA_LOADING';

export const IS_FETCHED = 'IS_FETCHED';
export const SHOW_DATA_UPDATING = 'SHOW_DATA_UPDATING';
export const SHOW_DATA_UPDATED = 'SHOW_DATA_UPDATED';

export const SHOW_TASK_DETAIL = 'SHOW_TASK_DETAIL';
export const HIDE_TASK_DETAIL = 'HIDE_TASK_DETAIL';
export const SHOW_USER_DETAIL = 'SHOW_USER_DETAIL';
export const HIDE_USER_DETAIL = 'HIDE_USER_DETAIL';

export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const INITIAL_DATA = 'INITIAL_DATA';
export const MODAL_ERROR = 'MODAL_ERROR';
export const CLOSE_MODAL_ERROR = 'CLOSE_MODAL_ERROR';

export const NEWTASK_FAILURE = 'NEWTASK_FAILURE';
export const CURRENT_PAGE = 'CURRENT_PAGE';

export const CATEGORY_LIST = 'CATEGORY_LIST';
export const SUBCATEGORY_LIST = 'SUBCATEGORY_LIST';
export const FC_LIST = 'FC_LIST';
export const PROJECT_LIST = 'PROJECT_LIST';
export const INITIAL_LOADED = 'INITIAL_LOADED';

export const MANAGED_BY = 'MANAGED_BY';
export const FS_STATUS = 'FS_STATUS';
export const PROJECT_TYPE = 'PROJECT_TYPE';

/* Users Page */

export const FILTER_USERS_FULFILLED = 'FILTER_USERS_FULFILLED';
export const DELETE_USER_FULFILLED = 'DELETE_USER_FULFILLED';


/* Tasks Page */

export const FILTER_TASKS_FULFILLED = 'FILTER_TASKS_FULFILLED';
export const NEW_TASK = 'NEW_TASK';
export const ADD_TASK = 'ADD_TASK';
export const NEW_TASK_DATA = 'NEW_TASK_DATA';
export const UPDATE_COMMENTS = 'UPDATE_COMMENTS';
export const TASK_ERROR = 'TASK_ERROR';


/* Timesheet Page */

export const SET_WEEK_DATA = 'SET_WEEK_DATA';
export const USER_TASK_LIST = 'USER_TASK_LIST';
export const USER_LIST = 'USER_LIST';
export const TIMESHEET_DATA = 'TIMESHEET_DATA';
export const PREV_TIMESHEET_DATA = 'PREV_TIMESHEET_DATA';
export const USER_SELECTED_TIMESHEET = 'USER_SELECTED_TIMESHEET';
export const CLOSE_TIMESHEET_POPUP = 'CLOSE_TIMESHEET_POPUP';
export const TIME_VALID = 'TIME_VALID';
export const TIMESHEET_DOWNLOAD = 'TIMESHEET_DOWNLOAD';


/* Dashboard page */

export const DASHBOARD_DATA = 'DASHBOARD_DATA';
export const DASHBOARD_USERLIST = 'DASHBOARD_USERLIST';
export const SWITCH_SELECTION = 'SWITCH_SELECTION';
export const DB_DD_CHANGE = 'DB_DD_CHANGE';


/* Future Scope page */

export const FILTER_FS_FULFILLED = 'FILTER_FS_FULFILLED';
export const HIDE_FS_DETAIL = 'HIDE_FS_DETAIL';
export const SHOW_FS_DETAIL = 'SHOW_FS_DETAIL';
export const NEW_FS = 'NEW_FS';
export const NEWFS_FAILURE = 'NEWFS_FAILURE';
export const SHOW_FSDATA_LOADING = 'SHOW_FSDATA_LOADING';
export const INITIAL_FS_DATA = 'INITIAL_FS_DATA';
export const FS_ERROR = 'FS_ERROR';
export const NEW_FS_DATA = 'NEW_FS_DATA';
export const FS_UPDATE_COMMENTS = 'FS_UPDATE_COMMENTS';
export const SHOW_COMMENTS_LOADING = 'SHOW_COMMENTS_LOADING';

/* Demand & Capacity */

export const DNC_DATA = 'DNC_DATA';

/* Productivity Report */
export const PRODUCTIVITY_DATA = 'PRODUCTIVITY_DATA';
export const TOGGLE_VACATION = 'TOGGLE_VACATION';
export const OVERALL_STATISTICS = 'OVERALL_STATISTICS';
export const IS_OVERALL_FETCHING = 'IS_OVERALL_FETCHING';
export const IS_OVERALL_FETCHED = 'IS_OVERALL_FETCHED';


/* Notifications */
export const NOTIF_TAB_SELECT = 'NOTIF_TAB_SELECT';
export const NOTIF_COMPOSE_NOTFILLED = 'NOTIF_COMPOSE_NOTFILLED';
export const NOTIF_SENT = 'NOTIF_SENT';
export const NOTIF_COMPOSE_UPDATE = 'NOTIF_COMPOSE_UPDATE';
export const NOTIF_ISLOADING = 'NOTIF_ISLOADING';
export const NOTIF_ISLOADED = 'NOTIF_ISLOADED';
export const NOTIF_NEW_LIST = 'NOTIF_NEW_LIST';
export const NOTIF_ARCHIVED_LIST = 'NOTIF_ARCHIVED_LIST';
export const NOTIF_SENT_LIST = 'NOTIF_SENT_LIST';
export const NOTIF_UPDATE_SUCCESS = 'NOTIF_UPDATE_SUCCESS';
export const UPDATE_LOADING = 'UPDATE_LOADING';
export const NOTIF_PUSH_NEW_LIST = 'NOTIF_PUSH_NEW_LIST';
export const NOTIF_PUSH_ARCHIVED_LIST = 'NOTIF_PUSH_ARCHIVED_LIST';
export const NOTIF_UPDATE_COUNTER = 'NOTIF_UPDATE_COUNTER';
